name: Blink

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Validate blink example is buildable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
      - name: Add rustc target for example
        run: rustup target add thumbv7m-none-eabi
      - name: Build Crates
        run: |
          cargo build
        env:
          RUSTFLAGS: --deny warnings

  ci:
    if: ${{ success() }}
    name: Finalize
    # all new jobs must be added to this list
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0